import logo from '../assets/img/logo.svg';
import slider_icon from '../assets/img/slider_icon.svg';
import right_arrow_icon from '../assets/img/right_arrow_icon.svg';
import Hero_bg1 from '../assets/img/Hero-bgbannerrd.webp';   
import Hero_bgMobb from '../assets/img/Hero-bgMob.png';
import Hero_bg2 from '../assets/img/Hero-bg2.webp';
import Hero_bg3 from '../assets/img/Hero-bg3.webp'; 
// import Hero_bg3 from '../assets/img/Hero-bannertesting.jpg';
import ArrowLaunch from '../assets/img/arrow-launchh.svg';
import Hero_icon_1 from '../assets/img/Hero-icon-1.svg';
import Hero_icon_2 from '../assets/img/Hero-icon-2.svg';
import Hero_icon_3 from '../assets/img/Hero-icon-3.svg';
import Hero_icon_4 from '../assets/img/Hero-icon-4.svg';
import archive1 from '../assets/img/archive1.webp';
import archive2 from '../assets/img/archive2.webp';
import archive3 from '../assets/img/archive3.webp';
import archive4 from '../assets/img/archive4.webp';
import ourGame1 from '../assets/img/ourgame1.webp';
import ourGame2 from '../assets/img/ourgame2.webp';
import company_1 from '../assets/img/igdb.svg';
import company_2 from '../assets/img/playtoearn.svg';
import company_3 from '../assets/img/mediapartl.svg';
import company_4 from '../assets/img/imdb.svg';
import merquee1 from '../assets/img/merquee1.webp';
import merquee2 from '../assets/img/merquee2.webp';
import merquee3 from '../assets/img/merquee3.webp';
import merquee4 from '../assets/img/merquee4.webp';
import merquee5 from '../assets/img/merquee5.webp';
import merquee6 from '../assets/img/merquee6.webp';
import merquee7 from '../assets/img/merquee7.webp';
import merquee8 from '../assets/img/merquee8.webp';
import merquee9 from '../assets/img/merquee9.webp';
import karnatkLogo from '../assets/img/karnatkLogo.png';
import KarnakLegacyLogo from '../assets/img/karnak-legacy-logoo.svg';
import Morraverse from '../assets/img/morraverse.svg';
import Comics from '../assets/img/comics.svg';
import Escort from '../assets/img/escort.svg';
import Web3Adoption from '../assets/img/web3-adoption.webp';
import MorraIcn from '../assets/img/morra-logo-icn.png';
import EpicAdventureImg from '../assets/img/epic-adventure.webp';
import DiverseWorlds from '../assets/img/diverse-worlds.webp';
import MultiplePlatforms from '../assets/img/multiple-platforms.webp';
import appleLogo from '../assets/img/appleLogo.svg';
import playstoreLogo from '../assets/img/playstoreLogo.svg';
import NewsArchive1 from '../assets/img/news-archive1.webp';
import NewsArchive2 from '../assets/img/news-archive2.webp';
import NewsArchive3 from '../assets/img/NewsArchive3.webp';
import Karrnakk from '../assets/img/karrnakk.png';
import Cancel from '../assets/img/cancel.svg';
import Uniswap from '../assets/img/uniswap.svg';
import Mexc from '../assets/img/mexc.svg';
import BraveWallet from '../assets/img/BraveWallet.svg';
import ArchiveBg from '../assets/img/Archive-bg.webp';
import MetaMask from '../assets/img/MetaMask.svg';
import Altura from '../assets/img/altura.webp';
import Chainlink from '../assets/img/chainlink.webp';
import DigitalArms from '../assets/img/digital-arms.webp';
import Gameswift from '../assets/img/gameswift.webp';
import Myria from '../assets/img/myria.webp';
import Polygon from '../assets/img/polygon.webp';
import ComicsIconn from '../assets/img/comicss-iconn.svg';
import PcIconn from '../assets/img/pcc-iconn.svg';
import AppleIconn from '../assets/img/apple-iconn.svg';
import PlayStoreIconn from '../assets/img/play-store-iconn.svg';
import NewsUser1 from '../assets/img/news-user1.webp';
import NewsDetails2Img from '../assets/img/news-details-2.webp';
import GameSection1Img1 from '../assets/img/game-section-1-img-1.webp';
import GameSection1Img2 from '../assets/img/game-section-1-img-2.webp';
import Games1Bg from '../assets/img/games1-background.webp';
import Games2BgMob from '../assets/img/mythiagamepagebgm.webp';
import Games1BgMob from '../assets/img/karnakgamepagemob.webp';
import PlayIcon from '../assets/img/play-icon.svg';
import FaceIcon from '../assets/img/face-icon.png';
import GameSection1Slider1 from '../assets/img/game-section-1-slider-1.webp';
import GameSection1Slider2 from '../assets/img/game-section-1-slider-2.webp';
import GameSection1Slider3 from '../assets/img/game-section-1-slider-3.webp';
import GameSection1Slider4 from '../assets/img/game-section-1-slider-4.webp';
import GameSection1Slider5 from '../assets/img/game-section-1-slider-5.webp';
import GameSection1SliderBg from '../assets/img/game-section-1-slider-bg.webp';
import Games2Bg from '../assets/img/games2-background.webp';
import Mythya from '../assets/img/mythya.webp';
import GameSection2Slider1 from '../assets/img/game-section-2-slider-1.webp';
import GameSection2Slider2 from '../assets/img/game-section-2-slider-2.webp';
import GameSection2Slider3 from '../assets/img/game-section-2-slider-3.webp';
import GameSection2Slider4 from '../assets/img/game-section-2-slider-4.webp';
import GameSection2Slider5 from '../assets/img/game-section-2-slider-5.webp';
import GameSection2SliderBg from '../assets/img/game-section-2-slider-bg.webp';
import GameSection2Img1 from '../assets/img/game-section-2-img-1.webp';
import GameSection2Img2 from '../assets/img/game-section-2-img-2.webp';

// import slide_image_1 from '../assets/img/apollo.png';
// import slide_image_2 from '../assets/img/nemesis.png';
// import slide_image_3 from '../assets/img/hercules.png';
// import slide_image_4 from '../assets/img/Ares.png';
// import slide_image_5 from '../assets/img/hermes.png';

// import slide_image_1 from '../assets/img/apollo11.png';
// import slide_image_2 from '../assets/img/apollo22.png';
// import slide_image_3 from '../assets/img/apollo33.png';
// import slide_image_4 from '../assets/img/apollo44.png';
// import slide_image_5 from '../assets/img/apollo55.png';

import slide_image_1 from '../assets/img/06.png';
import slide_image_2 from '../assets/img/07.png';
import slide_image_3 from '../assets/img/03.png';
import slide_image_4 from '../assets/img/04.png';
import slide_image_5 from '../assets/img/02.png';
// import slide_image_6 from '../assets/img/06.png';
import slide_image_7 from '../assets/img/01.png';



import UnityIconn from '../assets/img/unity-iconn.svg';
import Web3Iconn from '../assets/img/web3-iconn.svg';
import PhotonIconn from '../assets/img/photon-iconn.svg';
import AwsIconn from '../assets/img/aws-iconn.svg';

import Unreal from '../assets/img/unreal-engine.svg';
import AndroidL from '../assets/img/androidl.svg';
import ImmutableL from '../assets/img/immutablel.svg';
import IosL from '../assets/img/iosl.svg';

export {ArrowLaunch,Games1BgMob,Games2BgMob,ComicsIconn,PcIconn,Unreal,AndroidL,ImmutableL,IosL,Uniswap,Mexc,UnityIconn,Web3Iconn,PhotonIconn,AwsIconn,slide_image_1,slide_image_2,slide_image_3,slide_image_4,slide_image_5,slide_image_7,Hero_bgMobb,GameSection2SliderBg,GameSection2Slider1,GameSection2Slider2,GameSection2Slider3,GameSection2Slider4,GameSection2Slider5,Mythya,Games2Bg,GameSection2Img1,GameSection2Img2,GameSection1SliderBg,GameSection1Slider1,GameSection1Slider2,GameSection1Slider3,GameSection1Slider4,GameSection1Slider5,FaceIcon,PlayIcon,Games1Bg,GameSection1Img1,GameSection1Img2,NewsDetails2Img,NewsUser1,Hero_bg2,Hero_bg3,PlayStoreIconn,AppleIconn,Polygon,Chainlink,Altura,DigitalArms,Gameswift,Myria,NewsArchive3,ArchiveBg,MetaMask,BraveWallet,Cancel,DiverseWorlds,MultiplePlatforms,Karrnakk,appleLogo,playstoreLogo,NewsArchive1,NewsArchive2,EpicAdventureImg,Web3Adoption,MorraIcn,Escort,Comics,Morraverse,KarnakLegacyLogo,karnatkLogo,merquee1,merquee2,merquee3,merquee4,merquee5,merquee6,merquee7,merquee8,merquee9,company_1,company_2,company_3,company_4,ourGame1,ourGame2,archive1,archive2,archive3,archive4,Hero_icon_1,Hero_icon_2,Hero_icon_3,Hero_icon_4,Hero_bg1,right_arrow_icon,slider_icon,logo};